### PR TITLE
Added media query to adjust to all screen sizes

### PR DESCRIPTION
**Pull request by devTam**
set overflow on body to hidden to remove scrollbars

### CODE REVIEW

**Comment by mmuhamadamirzaidi** [comment]
Tomorrow I check okayy, because this os my work repo @devTam

**Comment by devTam** [comment]
alright

**Comment by mmuhamadamirzaidi-work** [comment]
Hi @devTam , it got some issue, you may try and check with developer tools if using Chrome browser. :D

result-1

**Comment by devTam** [comment]
I will check and push the update okay?

**Comment by mmuhamadamirzaidi** [comment]
> I will check and push the update okay?

Okayy @devTam :D

**Comment by devTam** [comment]
fixed it

**Pull request merged**
